language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

matrix:
  allow_failures:
    # As of 2013-11-02 there are a lot of dependencies
    # that still fail their own test suites on 5.18.
    - perl: "5.18"

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
  irc: "irc.perl.org#metacpan"

env:
  # we use a non-standard port to avoid trashing production
  # but travis will have it running on the standard port.
  - METACPAN_ES_TEST_PORT=9200

before_install:
  - cpanm -n Devel::Cover::Report::Coveralls

script:
  - perl Makefile.PL && cover -test -report coveralls

before_script:
  - "perl -i -pe 's/(servers :)9900/$1$ENV{METACPAN_ES_TEST_PORT}/' metacpan_server_testing.conf"

services:
  - elasticsearch
