language: perl
perl:
  - "5.22"

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
  irc: "irc.perl.org#metacpan-infra"

env:
  global:
    # We use a non-standard port to avoid trashing production
    # but travis will have it running on the standard port.
    - ES=localhost:9200
    - ES_TEST=localhost:9200

    # Instantiate Catalyst models using metacpan_server_testing.conf
    - METACPAN_SERVER_CONFIG_LOCAL_SUFFIX=testing

    - DEVEL_COVER_OPTIONS="-ignore,^local/"
    - PERL_CARTON_PATH=$HOME/local

    - DOCKER_IMAGE_NAME=metacpan-api
  matrix:
    - CPAN_RESOLVER=metadb PERL_CARTON_PATH=$HOME/no-snapshot HARNESS_VERBOSE=1
    - CPAN_RESOLVER=snapshot BUILD_DOCKER=yes

matrix:
  allow_failures:
    - env: CPAN_RESOLVER=metadb PERL_CARTON_PATH=$HOME/no-snapshot HARNESS_VERBOSE=1
  fast_finish: true

addons:
  apt:
    packages:
    # libgmp-dev required by Net::OpenID::Consumer
    - libgmp-dev
    # postgresql-server-dev-all is required by DBD::Pg
    - postgresql-server-dev-all

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init

  - bin/docker-elasticsearch /tmp/metacpan.yml /tmp/es 127.0.0.1:9200

  - cpanm -n Carton
  - cpanm -n App::cpm

  # Carton refuses to update Safe.pm to the version specified in the cpanfile and the
  # version that's core in 5.16 is too old (it fails to work with Devel::Cover).
  - cpanm -n Safe@2.35

install:
  - AUTHOR_TESTING=0 cpm install -L $PERL_CARTON_PATH --resolver $CPAN_RESOLVER --workers $(test-jobs) || (tail -n 500 -f ~/.perl-cpm/build.log; false)

before_script:
  - bin/wait-for-open http://$ES_TEST/
  - coverage-setup

script:
  - carton exec prove -It/lib -lr -j$(test-jobs) t

after_success:
  - coverage-report

#after_failure:
#  - cat ~/.cpanm/build.log

services:
  - docker

## Build and push a docker image in production
deploy:
  - provider: script
    script:
      - deploy/build.sh
    on:
      branch: master
      condition: $BUILD_DOCKER = 'yes'
  - provider: script
    script:
      - deploy/push.sh
    on:
      branch: master
      condition: $BUILD_DOCKER = 'yes'

# caching /local should save about 5 minutes in module install time
cache:
  directories:
    - $HOME/local
    - local
    - ~/perl5
    - t/var/darkpan
